Repository vJechsmayr/NewWorkApp, pull requests merged in 2022-10, with the labels that each got.

#5 Angular Project Setup
  NewWorkApplication_Angular/.browserslistrc
  NewWorkApplication_Angular/.editorconfig
  NewWorkApplication_Angular/.gitignore
  NewWorkApplication_Angular/.vscode/extensions.json
  NewWorkApplication_Angular/.vscode/launch.json
  NewWorkApplication_Angular/.vscode/tasks.json
  NewWorkApplication_Angular/README.md
  NewWorkApplication_Angular/angular.json
  NewWorkApplication_Angular/karma.conf.js
  NewWorkApplication_Angular/package-lock.json
  NewWorkApplication_Angular/package.json
  NewWorkApplication_Angular/src/app/app-routing.module.ts
  NewWorkApplication_Angular/src/app/app.component.html
  NewWorkApplication_Angular/src/app/app.component.scss
  NewWorkApplication_Angular/src/app/app.component.spec.ts
  NewWorkApplication_Angular/src/app/app.component.ts
  NewWorkApplication_Angular/src/app/app.module.ts
  NewWorkApplication_Angular/src/assets/.gitkeep
  NewWorkApplication_Angular/src/environments/environment.prod.ts
  NewWorkApplication_Angular/src/environments/environment.ts
  NewWorkApplication_Angular/src/favicon.ico
  NewWorkApplication_Angular/src/index.html
  NewWorkApplication_Angular/src/main.ts
  NewWorkApplication_Angular/src/polyfills.ts
  NewWorkApplication_Angular/src/styles.scss
  NewWorkApplication_Angular/src/test.ts
  NewWorkApplication_Angular/tsconfig.app.json
  NewWorkApplication_Angular/tsconfig.json
  NewWorkApplication_Angular/tsconfig.spec.json
Labels: hacktoberfest, no-code, low-code, hacktoberfest-accepted

#6 Update README.md
  README.md
Labels: hacktoberfest, no-code, low-code, hacktoberfest-accepted

#7 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#9 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, no-code, low-code, hacktoberfest-accepted
